tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jmhobbs/parrot"
tap "rcmdnk/file"
tap "zegervdv/zathura"
cask "osxfuse"
brew "automake"
brew "bat"
brew "figlet"
brew "ghostscript"
brew "gibo"
brew "git"
brew "git-lfs"
brew "go"
brew "openssl"
brew "googler"
brew "gopass"
brew "htop"
brew "hub"
brew "libtool"
brew "imagemagick"
brew "lftp"
brew "libimobiledevice", args: ["HEAD"]
brew "libzip"
brew "lolcat"
brew "mas"
brew "meson", args: ["HEAD"]
brew "neovim"
brew "nkf"
brew "node"
brew "p7zip"
brew "prettyping"
brew "r"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "ruby", link: true
brew "sshfs"
brew "telnet"
brew "tig"
brew "tmux"
brew "tor"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"
brew "jmhobbs/parrot/terminal-parrot"
brew "zegervdv/zathura/zathura"
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "basictex"
cask "bettertouchtool"
cask "bibdesk"
cask "boostnote"
cask "calibre"
cask "cmd-eikana"
cask "dash"
cask "firefox"
cask "flux"
cask "iterm2"
cask "java"
cask "jupyter-notebook-viewer"
cask "latexit"
cask "mendeley"
cask "oni"
cask "sequel-pro"
cask "slack"
cask "vagrant"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "wireshark"
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Mathpix Snipping Tool", id: 1349670778
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
